server:
  port: 8084

spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    platform: h2
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb1;MODE=PostgreSQL;INIT=RUNSCRIPT FROM 'classpath:data.sql'
    username: sa
    password: 123123
  h2:
    console:
      enabled: true
      path: /console/